/**
 * See fleece/COPYRIGHT for copyright information.
 *
 * This file is a part of Fleece.
 *
 * Fleece is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 3.0 of the License, or (at your option)
 * any later version.
 *  
 * This software is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this software; if not, see www.gnu.org/licenses
 */

#include "Info.h"
#include "fleece.h"

void Info::printOptions() {

   std::cout << "\
\
Copyright 2016 Nathan H. Jay\n\n\
Fleece is free software; you can redistribute it and/or modify it under the\n\
terms of the GNU Lesser General Public License as published by the Free\n\
Software Foundation; either version 3.0 of the License, or (at your option)\n\
any later version.\n\n\
This software is distributed in the hope that it will be useful, but WITHOUT\n\
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS\n\
FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more\n\
details.\n\n\
You should have received a copy of the GNU Lesser General Public License\n\
along with this software; if not, see www.gnu.org/licenses\n\n";

    std::cout << "Example usage:\n";
    std::cout << "./fleece -as=/usr/bin/as -objdump=/usr/bin/objdump -norm -n=10 -arch=x86_64 -decoders=xed,gnu\n";
    std::cout << "\nFleece arguments:\n";


    std::cout << "\nDATA:\n";
    std::cout << "\n  byte_source | ./fleece\n";
    std::cout << "    To pipe bytes from a file or program into fleece\n";
    std::cout << "\n  -rand\n";
    std::cout << "    Use only random instructions, do not generate extra inputs.\n";
    std::cout << "\n  -n=n\n";
    std::cout << "    Generate n random byte sequences to begin input generation.\n";
    std::cout << "\n  -len=n\n";
    std::cout << "    Length of each instruction. Shorter instructions should be padded to this length\n";
   
    std::cout << "\n\nOPTIONS:\n";
    std::cout << "\n  -arch=architecture\n";
    std::cout << "    (MANDATORY) choose from: x84_64, aarch64, ppc\n";
    std::cout << "\n  -decoders=decoder1,decoder2\n";
    std::cout << "    (MANDATORY) choose from: xed, dyninst, llvm, gnu, capstone\n\n";
  
    std::cout << "\n\nREASSEMBLY:\n";
    std::cout << "\n  -as=/absolute/path/to/assembler (MANDATORY)\n";
    std::cout << "\n  -asopt=comma sep list of assembler options\n";
    std::cout << "    ex. -asopt=-mregname,-mpower9\n";
    std::cout << "\n  -asf=/abosulte/path/to/temporary/asm/file\n";
    std::cout << "    default: /tmp/tmp.s\n";
    std::cout << "\n  -objdump=/absolute/path/to/objdump (MANDATORY)\n";

    std::cout << "\n\nOUTPUT & REPORTING:\n";
    std::cout << "\n  -o=output_dir\n";
    std::cout << "    The directory where output shoul be place (relative or absolute).\n";
    std::cout << "    default: ./fleece_results/\n";
    std::cout << "\n  -t\n";
    std::cout << "    Shows timing information at the end of execution\n";
    std::cout << "\n  -norm\n";
    std::cout << "    Normalizes the output of decoders partially. Assembly detects other equivalences.\n";
    std::cout << "\n  -bytes\n";
    std::cout << "    Prints the raw bytes of an instruction before decoding.\n";
    std::cout << "\n  -seed=n\n";
    std::cout << "    Specifies the seed for random instruction generation.\n";
    std::cout << "\n  -pig\n";
    std::cout << "    Prints input generated by each decoder.\n";
}

void Info::printVersion() {
    std::cout << "Fleece version: " << FLEECE_VERSION_STRING << std::endl;
}
